# Site settings
title: Explainable Graph-Based Machine Learning
email: your-email@domain.com
url: https://example.github.io
description: "Explainable Graph-Based Machine Learning Workshop at the 3rd Conference on Automated Knowledge Base Construction (AKBC 2021)."
keywords: "your keywords, separated by commas"
skills: "Virtual Workshop at the 3rd Conference on Automated Knowledge Base Construction (AKBC 2021)<br>October 8, 2021<br>" # Please visit the following <a href="https://kb-mm-2020.github.io">link for 2nd edition of KBMM</a>"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1E90FF #80B3FF
  primary-rgb: "30,144,255" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  #copyright: Dr. Henry Jekyll
  #location: Location
  #social: Around the Web
  #credits: Credits


# Postal address (add as many lines as necessary)
address:
  - line: UCI, Irvine
  - line: CA 92697

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
